spring:
  datasource:
    #    url: jdbc:mysql://127.0.0.1:3308/feelGood?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&autoReconnect=true
    url: jdbc:mysql://feelgooddb/feelGood?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&autoReconnect=true
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: on

logging:
  level:
    org:
      flywaydb: debug

event:
  price:
    tier_1: 2500.0
    tier_2: 5000.0
    tier_3: 6500.0
    tier_4: 8900.0
    tier_5: 12000.0